/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "background": "#f7f9fb",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "primary-fixed": "#d4e3ff",
        "inverse-on-surface": "#eff1f3",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d8dadc",
        "surface-tint": "#005faf",
        "on-tertiary-container": "#fcfdff",
        "tertiary-fixed-dim": "#b4cad6",
        "on-primary-fixed": "#001c3a",
        "tertiary-container": "#637883",
        "primary-container": "#1976d2",
        "on-primary-container": "#fffdff",
        "inverse-surface": "#2d3133",
        "primary": "#005dac",
        "surface-variant": "#e0e3e5",
        "surface-container-high": "#e6e8ea",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#a5c8ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#217128",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "secondary-container": "#a0f399",
        "on-secondary-fixed-variant": "#005312",
        "surface-container-low": "#f2f4f6",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-container": "#eceef0",
        "error-container": "#ffdad6",
        "secondary-fixed": "#a3f69c",
        "on-primary-fixed-variant": "#004786",
        "on-surface-variant": "#414752",
        "inverse-primary": "#a5c8ff",
        "on-tertiary-fixed": "#071e27",
        "outline": "#717783",
        "secondary": "#1b6d24",
        "outline-variant": "#c1c6d4",
        "on-secondary-fixed": "#002204",
        "tertiary-fixed": "#cfe6f2",
        "on-tertiary-fixed-variant": "#354a53",
        "on-background": "#191c1e",
        "tertiary": "#4a5f69",
        "secondary-fixed-dim": "#88d982"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
