-- =============================================================================
-- PharmaLabel Designer — Local PostgreSQL Setup Script (REFACTORED)
-- =============================================================================
-- Generated by: Antigravity (mirrored from Supabase project: LABEL DESIGNER)
-- PostgreSQL Version: 17+
-- =============================================================================

-- ── 0.  Setup Schemas and Extensions ──────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS "pgcrypto" SCHEMA extensions;

-- =============================================================================
-- SECTION 1: CORE TABLES
-- =============================================================================

-- ── 1.1 roles ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.roles (
    id   UUID PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    name TEXT UNIQUE NOT NULL
);

-- ── 1.2 users ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.users (
    id                    UUID        PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    username              TEXT        NOT NULL UNIQUE,
    email                 TEXT        NOT NULL UNIQUE,
    password_hash         TEXT        NOT NULL,
    role_id               UUID        REFERENCES public.roles(id),
    status                TEXT        DEFAULT 'ACTIVE',
    failed_login_attempts INTEGER     DEFAULT 0,
    locked_until          TIMESTAMPTZ,
    password_changed_at   TIMESTAMPTZ DEFAULT now(),
    must_change_password  BOOLEAN     DEFAULT true,
    created_at            TIMESTAMPTZ DEFAULT now()
);

-- ── 1.3 permissions ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.permissions (
    id      UUID    PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    role_id UUID    REFERENCES public.roles(id),
    module  TEXT    NOT NULL,
    event   TEXT    NOT NULL,
    allowed BOOLEAN DEFAULT true
);

-- =============================================================================
-- SECTION 2: SETUP MASTER TABLES
-- =============================================================================

-- ── 2.1 languages ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.languages (
    id        UUID PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    name      TEXT NOT NULL,
    code      TEXT NOT NULL UNIQUE,
    direction TEXT CHECK (direction IN ('LTR', 'RTL')),
    status    TEXT DEFAULT 'ACTIVE'
);

-- ── 2.2 label_stocks ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.label_stocks (
    id          UUID PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    name        TEXT NOT NULL,
    length      NUMERIC,
    width       NUMERIC,
    height      NUMERIC,
    description TEXT
);

-- ── 2.3 objects ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.objects (
    id       UUID PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    name     TEXT NOT NULL,
    type     TEXT,
    file_url TEXT,
    status   TEXT DEFAULT 'ACTIVE'
);

-- ── 2.4 placeholders ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.placeholders (
    id           UUID PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    name         TEXT NOT NULL,
    type         TEXT CHECK (type IN ('DATA', 'FREE_TEXT', 'RUNTIME', 'VISIT')),
    mapping_key  TEXT,
    format_rules JSONB
);

-- ── 2.5 phrases ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.phrases (
    id          UUID PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    phrase_key  TEXT UNIQUE NOT NULL,
    default_text TEXT
);

-- ── 2.6 translations ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.translations (
    id              UUID PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    phrase_id       UUID REFERENCES public.phrases(id) ON DELETE CASCADE,
    language_id     UUID REFERENCES public.languages(id) ON DELETE CASCADE,
    translated_text TEXT,
    UNIQUE(phrase_id, language_id)
);

-- =============================================================================
-- SECTION 3: LABEL DESIGN TABLES
-- =============================================================================

-- ── 3.1 labels ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.labels (
    id             UUID        PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    name           TEXT        NOT NULL,
    brand          TEXT,
    category       TEXT,
    image_url      TEXT,
    label_stock_id UUID        REFERENCES public.label_stocks(id),
    created_by     UUID        REFERENCES public.users(id),
    status         TEXT        DEFAULT 'DRAFT',
    created_at     TIMESTAMPTZ DEFAULT now(),
    updated_at     TIMESTAMPTZ DEFAULT now()
);

-- ── 3.2 label_versions ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.label_versions (
    id            UUID        PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    label_id      UUID        REFERENCES public.labels(id) ON DELETE CASCADE,
    version_no    INTEGER     NOT NULL,
    design_json   JSONB       NOT NULL,
    created_by    UUID        REFERENCES public.users(id),
    created_at    TIMESTAMPTZ DEFAULT now(),
    UNIQUE(label_id, version_no)
);

-- =============================================================================
-- SECTION 4: WORKFLOW & SYSTEM TABLES
-- =============================================================================

-- ── 4.1 approvals ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.approvals (
    id          UUID        PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    entity_type TEXT        NOT NULL,
    entity_id   UUID        NOT NULL,
    status      TEXT        DEFAULT 'PENDING',
    approved_by UUID        REFERENCES public.users(id),
    approved_at TIMESTAMPTZ
);

-- ── 4.2 electronic_signatures ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.electronic_signatures (
    id          UUID        PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    user_id     UUID        REFERENCES public.users(id),
    entity_type TEXT        NOT NULL,
    entity_id   UUID        NOT NULL,
    meaning     TEXT        NOT NULL,
    signed_at   TIMESTAMPTZ DEFAULT now()
);

-- ── 4.3 audit_logs ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id         UUID        PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    user_id    UUID        REFERENCES public.users(id),
    action     TEXT        NOT NULL,
    module     TEXT        NOT NULL,
    entity_id  UUID,
    old_data   JSONB,
    new_data   JSONB,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ── 4.4 system_config ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.system_config (
    id           UUID        PRIMARY KEY DEFAULT extensions.gen_random_uuid(),
    config_key   TEXT        NOT NULL UNIQUE,
    config_value TEXT,
    updated_at   TIMESTAMPTZ DEFAULT now()
);

-- =============================================================================
-- SECTION 5: INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users(username);
CREATE INDEX IF NOT EXISTS idx_users_role_id ON public.users(role_id);
CREATE INDEX IF NOT EXISTS idx_permissions_role_id ON public.permissions(role_id);
CREATE INDEX IF NOT EXISTS idx_translations_phrase_id ON public.translations(phrase_id);
CREATE INDEX IF NOT EXISTS idx_translations_language_id ON public.translations(language_id);
CREATE INDEX IF NOT EXISTS idx_labels_stock_id ON public.labels(label_stock_id);
CREATE INDEX IF NOT EXISTS idx_labels_created_by ON public.labels(created_by);
CREATE INDEX IF NOT EXISTS idx_label_versions_label_id ON public.label_versions(label_id);
CREATE INDEX IF NOT EXISTS idx_label_versions_created_by ON public.label_versions(created_by);
CREATE INDEX IF NOT EXISTS idx_approvals_entity_id ON public.approvals(entity_id);
CREATE INDEX IF NOT EXISTS idx_electronic_signatures_user_id ON public.electronic_signatures(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON public.audit_logs(user_id);

-- =============================================================================
-- SECTION 6: TRIGGERS
-- =============================================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_labels_updated_at ON public.labels;
CREATE TRIGGER trg_labels_updated_at
    BEFORE UPDATE ON public.labels
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- =============================================================================
-- SECTION 7: SEED DATA
-- =============================================================================

-- Roles
INSERT INTO public.roles (id, name) VALUES
  ('d68e4294-eff5-4f3a-b6c2-3adff348e863', 'ADMIN'),
  ('0446db85-60cd-4f5e-8125-b049531c7716', 'REVIEWER'),
  ('39c97678-04c1-4d46-932d-959502633631', 'DESIGNER')
ON CONFLICT (name) DO NOTHING;

-- Initial Admin User
INSERT INTO public.users (
  id, username, email, password_hash, role_id, status, must_change_password
) VALUES (
  '7ff60cdf-9814-4a32-b956-a9b1ed9764a8', 'clinicalAdmin', 'clinicalAdmin@gmail.com',
  '$2a$10$IvTQw4Z4kysPIMPt2314qeo99SJjEfOKJVR/3AWfGvNx7bRmnrtRy',
  'd68e4294-eff5-4f3a-b6c2-3adff348e863', 'ACTIVE', false
) ON CONFLICT (username) DO NOTHING;

-- System User
INSERT INTO public.users (id, username, email, password_hash, status, must_change_password)
VALUES ('00000000-0000-0000-0000-000000000000', 'system', 'system@internal.label', 'N/A', 'ACTIVE', false)
ON CONFLICT (username) DO NOTHING;

-- Languages
INSERT INTO public.languages (name, code, direction, status) VALUES
  ('English', 'en', 'LTR', 'ACTIVE'),
  ('Spanish', 'es', 'LTR', 'ACTIVE')
ON CONFLICT (code) DO NOTHING;

-- System Config
INSERT INTO public.system_config (config_key, config_value) VALUES
  ('sod.prevent_same_user_approve', 'true'),
  ('audit.log_limit_days', '365')
ON CONFLICT (config_key) DO NOTHING;

-- =============================================================================
-- DONE. New Refactored Database is ready.
-- =============================================================================
